// @ts-nocheck
// Event payload types not in commands:
export type DownloadProgressPayload = { variant_id: string; downloaded_bytes: number; total_bytes: number | null; speed_bps: number; eta_secs: number | null }
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 获取当前激活主题名称
 */
async getCurrentTheme() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_theme") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置当前激活主题
 */
async setCurrentTheme(name: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_theme", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列举内置主题信息
 */
async listBuiltinThemes() : Promise<Result<ThemeInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_builtin_themes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<AppConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConfig(partial: PartialAppConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_config", { partial }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetConfig() : Promise<Result<AppConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出所有模型变体及其下载/激活状态
 */
async listModelVariants() : Promise<Result<ModelVariant[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_model_variants") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 触发后台下载（非阻塞），立即返回
 */
async downloadModel(variantId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { variantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消正在进行的下载
 */
async cancelDownload(variantId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { variantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除已下载的模型文件
 */
async deleteModel(variantId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { variantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 切换激活模型（持久化到 AppConfig，下次推理时生效）
 */
async setActiveModel(variantId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { variantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Poll and consume one download error (pop-once semantics). Frontend calls every 2s during download.
 * Returns Some(error_message) if error exists, None if not.
 */
async getDownloadError(variantId: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_download_error", { variantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出系统可用音频输入设备（前端设备下拉选择器数据源）
 */
async listAudioDevices() : Promise<Result<AudioDevice[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 开始实时录音。立即返回 session_id，后续通过 Tauri 事件通知状态变化。
 */
async startRealtime(config: RealtimeConfig) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_realtime", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseRealtime(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_realtime", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeRealtime(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_realtime", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 停止录音，保存 WAV 文件并写入数据库，返回 recording_id
 */
async stopRealtime(sessionId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_realtime", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 前端轮询当前音频 RMS 电平（0.0–1.0）。
 * Tauri 事件系统在 macOS 开发模式下不可靠，改用轮询方案。
 * 前端每 100ms 调用一次，录音结束后停止调用。
 */
async getAudioLevel() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_level") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 前端轮询当前会话已转录的 segments。
 * 同一套轮询方案替代 Tauri 事件（事件在 macOS 开发模式下不可靠）。
 * 前端每 500ms 调用一次，stop 后再调用一次获取最终 segments。
 */
async getRealtimeSegments(sessionId: string) : Promise<Result<SegmentPayload[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_realtime_segments", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecordingStatus() : Promise<Result<RecordingStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recording_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出所有录音，按创建时间倒序
 */
async listRecordings() : Promise<Result<RecordingItem[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recordings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all text assets for a document, ordered by role priority
 */
async getDocumentAssets(documentId: string) : Promise<Result<DocumentAsset[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_document_assets", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 按需为录音创建 workspace_document（幂等）。
 * 若已存在则直接返回 document_id；否则创建新的 document + transcript asset（从分段拼接）。
 */
async ensureDocumentForRecording(recordingId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_document_for_recording", { recordingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * UPSERT 一条 text asset，同时将内容写入本地 .md 文件（vault_path/notes/{title}/{role}.md）。
 */
async updateDocumentAsset(documentId: string, role: string, content: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_document_asset", { documentId, role, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除录音。also_delete_document=true 时同时删除关联的 workspace_document（级联删除 assets）。
 * 同时删除磁盘上的 WAV 文件（失败不报错）。
 */
async deleteRecording(recordingId: string, alsoDeleteDocument: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_recording", { recordingId, alsoDeleteDocument }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 提交 LLM 任务，立即返回 task_id
 */
async submitLlmTask(request: LlmTaskRequest) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_llm_task", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消 LLM 任务
 */
async cancelLlmTask(taskId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_llm_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 查询 LLM 引擎状态
 */
async getLlmEngineStatus() : Promise<Result<LlmEngineStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_llm_engine_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 查询某文档的 LLM 任务历史
 */
async listDocumentLlmTasks(documentId: string) : Promise<Result<LlmTaskRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_document_llm_tasks", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ensureSystemFolders() : Promise<Result<SystemFolderIds, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_system_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFoldersWithDocuments() : Promise<Result<FolderNode[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_folders_with_documents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(parentId: string | null, name: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { parentId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFolder(folderId: string, name: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_folder", { folderId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFolder(folderId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveDocumentToFolder(documentId: string, folderId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_document_to_folder", { documentId, folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameDocument(documentId: string, title: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_document", { documentId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDocument(documentId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_document", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSegmentsWithTranslations(recordingId: string, language: string | null) : Promise<Result<SegmentRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_segments_with_translations", { recordingId, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSegmentTiming(segmentId: number, startMs: number, endMs: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_segment_timing", { segmentId, startMs, endMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSegmentTranslation(segmentId: number, language: string, text: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_segment_translation", { segmentId, language, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async alignTranslationToSegments(documentId: string, language: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("align_translation_to_segments", { documentId, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSubtitle(recordingId: string, format: SubtitleFormat, language: SubtitleLanguage) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_subtitle", { recordingId, format, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type SystemFolderIds = { inbox_id: string; batch_task_id: string }
export type DocumentSummary = { id: string; title: string; source_type: string; recording_id: string | null; created_at: number }
export type FolderNode = { id: string; name: string; folder_kind: string; is_system: boolean; children: FolderNode[]; documents: DocumentSummary[] }
export type SegmentRow = { id: number; recording_id: string; start_ms: number; end_ms: number; text: string; translated_text: string | null }
export type SubtitleFormat = "srt" | "vtt" | "lrc"
export type SubtitleLanguage = { type: "original" } | { type: "translation"; data: string }

/**
 * Full application configuration. Stored as a single JSON blob
 * in `app_settings` under the key `"app_config"`.
 */
export type AppConfig = { 
/**
 * UI locale. Default: "zh_CN"
 */
locale: string; 
/**
 * Active theme display name. Default: "Tokyo Night"
 */
active_theme: string; 
/**
 * Active whisper model variant id. Default: "whisper/base"
 */
active_whisper_model: string; 
/**
 * Active LLM model variant id. Default: "llm/qwen2.5-3b-q4"
 */
active_llm_model: string; 
/**
 * LLM context window size in tokens. Default: 4096
 */
llm_context_size: number; 
/**
 * Path to the vault directory (workspace documents). Default: {APP_DATA}/vault
 */
vault_path: string; 
/**
 * Path to the recordings directory (audio WAV files). Default: {APP_DATA}/recordings
 */
recordings_path: string; 
/**
 * Default recording mode. Values: "record_only" | "transcribe_only" | "transcribe_and_translate"
 * Default: "transcribe_only"
 */
default_recording_mode: string; 
/**
 * Default transcription language. None = auto-detect.
 */
default_language: string | null; 
/**
 * Default translation target language. Default: "en"
 */
default_target_language: string; 
/**
 * VAD energy threshold (0.0–1.0). Default: 0.02
 */
vad_threshold: number; 
/**
 * Automatically trigger AI processing after recording stops. Default: false
 */
auto_llm_on_stop: boolean; 
/**
 * Last microphone device ID used. None = not yet set (use system default). Default: None
 */
last_used_device_id: string | null; 
/**
 * Default LLM task type. Values: "summary" | "meeting_brief". Default: "summary"
 */
default_llm_task: string; 
/**
 * Model download mirror.
 * "" / "default" = use URLs as-is from models.toml (huggingface.co)
 * "hf-mirror"    = replace huggingface.co with hf-mirror.com (China-friendly)
 * Custom URL     = replace huggingface.co with this base URL
 */
model_mirror: string }
export type AppError = { kind: "Audio"; message: string } | { kind: "Transcription"; message: string } | { kind: "Llm"; message: string } | { kind: "Storage"; message: string } | { kind: "Io"; message: string } | { kind: "Model"; message: string } | { kind: "Workspace"; message: string } | { kind: "NotFound"; message: string } | { kind: "Validation"; message: string } | { kind: "ChannelClosed" }
export type AudioDevice = { id: string; name: string; is_default: boolean; sample_rate: number; channels: number }
/**
 * Single document text asset (transcript, summary, meeting_brief, etc.)
 */
export type DocumentAsset = { id: string; document_id: string; role: string; content: string; created_at: number; updated_at: number }
export type LlmEngineStatus = { status: "not_loaded" } | { status: "loading"; model_id: string } | { status: "ready"; model_id: string; loaded_at: number } | { status: "error"; message: string }
export type LlmTaskRequest = { document_id: string; task_type: LlmTaskType; 
/**
 * Optional role hint for get_best_text (e.g. "transcript")
 */
text_role_hint: string | null }
export type LlmTaskRow = { id: string; document_id: string; task_type: string; status: string; result_text: string | null; error_msg: string | null; created_at: number; completed_at: number | null }
export type LlmTaskType = { type: "summary" } | { type: "meeting_brief" } | { type: "translation"; data: { target_language: string } } | { type: "qa"; data: { question: string } }
/**
 * 单个模型变体的完整状态（`list_model_variants` 返回值）
 */
export type ModelVariant = { 
/**
 * 格式："whisper/base" 或 "llm/qwen2.5-3b-q4"
 */
variant_id: string; 
/**
 * "whisper" | "llm"
 */
model_type: string; name: string; description: string; size_bytes: number; 
/**
 * 格式化后的大小字符串，如 "142 MB"
 */
size_display: string; is_downloaded: boolean; 
/**
 * 当前已加载（激活）的模型
 */
is_active: boolean; 
/**
 * SHA256 是否已配置（false = 占位符，禁止下载）
 */
sha256_valid: boolean }
/**
 * Partial update payload. Every field is `Option<T>`.
 * `None` means "do not update this field".
 * For `default_language`, `Some(None)` clears the value; `Some(Some("zh"))` sets it.
 * 
 * `skip_serializing_if = "Option::is_none"` ensures that undefined fields
 * from the frontend are absent from the serialized JSON.
 */
export type PartialAppConfig = { locale?: string | null; active_theme?: string | null; active_whisper_model?: string | null; active_llm_model?: string | null; llm_context_size?: number | null; vault_path?: string | null; recordings_path?: string | null; default_recording_mode?: string | null; 
/**
 * `Some(None)` clears the language (auto-detect); `Some(Some("zh"))` sets it.
 */
default_language?: string | null; default_target_language?: string | null; vad_threshold?: number | null; auto_llm_on_stop?: boolean | null; last_used_device_id?: string | null; default_llm_task?: string | null; model_mirror?: string | null }
export type RealtimeConfig = { device_id: string | null; language: string | null; mode: RecordingMode; vad_threshold: number }
/**
 * 单条录音摘要（用于 Workspace 列表）
 */
export type RecordingItem = { id: string; title: string; file_path: string; duration_ms: number; language: string; created_at: number; 
/**
 * 转写全文拼接（来自 workspace_text_assets.content），无则空串
 */
transcript: string; 
/**
 * workspace_documents.id for this recording (None if not yet indexed)
 */
document_id: string | null }
export type RecordingMode = "record_only" | "transcribe_only" | { transcribe_and_translate: { target_language: string } }
export type RecordingStatus = { status: "idle" } | { status: "recording"; session_id: string; started_at: number } | { status: "paused"; session_id: string } | { status: "stopped"; session_id: string; recording_id: string }
export type SegmentPayload = { id: number; recording_session_id: string; start_ms: number; end_ms: number; text: string; language: string; is_partial: boolean }
/**
 * 主题描述符，仅含元信息（不含完整 token 数据，token 由前端直接读取 JSON 文件）
 */
export type ThemeInfo = { name: string; type: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
