// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta).
// It is NOT safe to manually edit this file (it will be overwritten on next build).
// Regenerate with: cd src-tauri && cargo build (debug mode triggers export_bindings())

import { invoke as tauriInvoke } from "@tauri-apps/api/core";

export const commands = {
  async getCurrentTheme(): Promise<string> {
    return tauriInvoke<string>("get_current_theme");
  },
  async setCurrentTheme(name: string): Promise<void> {
    return tauriInvoke<void>("set_current_theme", { name });
  },
  async listBuiltinThemes(): Promise<Array<{ name: string; type: string }>> {
    return tauriInvoke<Array<{ name: string; type: string }>>("list_builtin_themes");
  },
  async getAppConfig(): Promise<{ theme: string; language: string }> {
    return tauriInvoke<{ theme: string; language: string }>("get_app_config");
  },
};
