
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 获取当前激活主题名称
 */
async getCurrentTheme() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_theme") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置当前激活主题
 */
async setCurrentTheme(name: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_theme", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列举内置主题信息
 */
async listBuiltinThemes() : Promise<Result<ThemeInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_builtin_themes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<AppConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConfig(partial: PartialAppConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_config", { partial }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetConfig() : Promise<Result<AppConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppConfig = {
    locale: string;
    active_theme: string;
    active_whisper_model: string;
    active_llm_model: string;
    llm_context_size: number;
    vault_path: string;
    recordings_path: string;
    default_recording_mode: string;
    default_language: string | null;
    default_target_language: string;
    vad_threshold: number;
    audio_chunk_ms: number;
    auto_llm_on_stop: boolean;
    default_llm_task: string;
}
export type PartialAppConfig = {
    locale?: string | null;
    active_theme?: string | null;
    active_whisper_model?: string | null;
    active_llm_model?: string | null;
    llm_context_size?: number | null;
    vault_path?: string | null;
    recordings_path?: string | null;
    default_recording_mode?: string | null;
    default_language?: string | null | undefined;
    default_target_language?: string | null;
    vad_threshold?: number | null;
    audio_chunk_ms?: number | null;
    auto_llm_on_stop?: boolean | null;
    default_llm_task?: string | null;
}
export type AppError = { kind: "Audio"; message: string } | { kind: "Transcription"; message: string } | { kind: "Llm"; message: string } | { kind: "Storage"; message: string } | { kind: "Io"; message: string } | { kind: "Model"; message: string } | { kind: "Workspace"; message: string } | { kind: "NotFound"; message: string } | { kind: "Validation"; message: string } | { kind: "ChannelClosed" }
/**
 * 主题描述符，仅含元信息（不含完整 token 数据，token 由前端直接读取 JSON 文件）
 */
export type ThemeInfo = { name: string; type: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";


export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

