# Pre-commit hooks configuration for EchoNote
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=10000"] # 10MB limit
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=100"]

  # Import sorting with isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]

  # Linting with flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
            "--max-line-length=100",
            "--extend-ignore=E203,W503", # Ignore conflicts with Black
            "--exclude=.git,__pycache__,build,dist,.venv,venv",
          ]

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args:
          [
            "--ignore-missing-imports",
            "--no-strict-optional",
            "--warn-redundant-casts",
            "--warn-unused-ignores",
          ]
        exclude: ^tests/

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^tests/

  # Docstring coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args:
          [
            "--verbose",
            "--fail-under=80",
            "--ignore-init-method",
            "--ignore-init-module",
            "--ignore-magic",
            "--ignore-module",
            "--ignore-private",
            "--ignore-nested-functions",
            "--exclude=tests",
          ]

# Configuration for specific hooks
default_language_version:
  python: python3.11

# Files to exclude from all hooks
exclude: |
  (?x)^(
      \.git/|
      \.venv/|
      venv/|
      build/|
      dist/|
      \.eggs/|
      .*\.egg-info/|
      __pycache__/|
      \.pytest_cache/|
      \.mypy_cache/|
      \.tox/|
      htmlcov/|
      models/|
      resources/|
      \.kiro/
  )

# Fail fast - stop running hooks after first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: "3.0.0"
