codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "examples/**/*"
  - "docs/**/*"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - ".venv/**"
  - "venv/**"
  - "build/**"
  - "dist/**"

flags:
  ubuntu-latest-py3.10:
    carryforward: true
  ubuntu-latest-py3.11:
    carryforward: true
  ubuntu-latest-py3.12:
    carryforward: true
  windows-latest-py3.10:
    carryforward: true
  windows-latest-py3.11:
    carryforward: true
  windows-latest-py3.12:
    carryforward: true
  macos-latest-py3.10:
    carryforward: true
  macos-latest-py3.11:
    carryforward: true
  macos-latest-py3.12:
    carryforward: true
