# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2025 EchoNote Contributors

"""
Centralized PySide6 imports for the entire EchoNote application.

This module provides a single location for all PySide6 imports used throughout
the application (Core, UI, and Utils layers), ensuring consistent import patterns
and preventing name errors.
"""

# Core Qt classes
from PySide6.QtCore import (
    Q_ARG,
    QCoreApplication,
    QDate,
    QDateTime,
    QEvent,
    QLocale,
    QMetaObject,
    QObject,
    QPoint,
    QRect,
    QRunnable,
    QSettings,
    QSize,
    Qt,
    QThread,
    QThreadPool,
    QTime,
    QTimer,
    QUrl,
    Signal,
    Slot,
)

# GUI classes
from PySide6.QtGui import (
    QAction,
    QBrush,
    QClipboard,
    QCloseEvent,
    QColor,
    QFocusEvent,
    QFont,
    QFontMetrics,
    QHideEvent,
    QIcon,
    QKeyEvent,
    QKeySequence,
    QMouseEvent,
    QMoveEvent,
    QPainter,
    QPaintEvent,
    QPalette,
    QPen,
    QPixmap,
    QResizeEvent,
    QShortcut,
    QShowEvent,
    QTextCharFormat,
    QTextCursor,
    QTextDocument,
)

# Widget classes
from PySide6.QtWidgets import (
    QAbstractItemView,
    QApplication,
    QButtonGroup,
    QCheckBox,
    QComboBox,
    QDateEdit,
    QDateTimeEdit,
    QDialog,
    QDoubleSpinBox,
    QFileDialog,
    QFormLayout,
    QFrame,
    QGraphicsOpacityEffect,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QInputDialog,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QMenu,
    QMessageBox,
    QPlainTextEdit,
    QProgressBar,
    QProgressDialog,
    QPushButton,
    QRadioButton,
    QScrollArea,
    QSizePolicy,
    QSlider,
    QSpacerItem,
    QSplashScreen,
    QSpinBox,
    QSplitter,
    QStackedWidget,
    QStyle,
    QTableWidget,
    QTableWidgetItem,
    QTabWidget,
    QTextEdit,
    QToolBar,
    QToolButton,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
)

# Multimedia classes (Optional depending on environment, but typically present in PySide6)
try:
    from PySide6.QtMultimedia import QAudioOutput, QMediaPlayer
    MULTIMEDIA_AVAILABLE = True
except ImportError:
    MULTIMEDIA_AVAILABLE = False
    QAudioOutput = None
    QMediaPlayer = None

# Re-export commonly used items for convenience
__all__ = [
    # QtCore
    "Q_ARG",
    "QCoreApplication",
    "QDate",
    "QDateTime",
    "QEvent",
    "QLocale",
    "QMetaObject",
    "QObject",
    "QPoint",
    "QRect",
    "QRunnable",
    "QSettings",
    "QSize",
    "Qt",
    "QThread",
    "QThreadPool",
    "QTime",
    "QTimer",
    "QUrl",
    "Signal",
    "Slot",
    # QtGui
    "QAction",
    "QBrush",
    "QClipboard",
    "QCloseEvent",
    "QColor",
    "QFocusEvent",
    "QFont",
    "QFontMetrics",
    "QHideEvent",
    "QIcon",
    "QKeyEvent",
    "QKeySequence",
    "QMouseEvent",
    "QMoveEvent",
    "QPainter",
    "QPaintEvent",
    "QPalette",
    "QPen",
    "QPixmap",
    "QResizeEvent",
    "QShortcut",
    "QShowEvent",
    "QTextCharFormat",
    "QTextCursor",
    "QTextDocument",
    # QtWidgets
    "QAbstractItemView",
    "QApplication",
    "QButtonGroup",
    "QCheckBox",
    "QComboBox",
    "QDateEdit",
    "QDateTimeEdit",
    "QDialog",
    "QDoubleSpinBox",
    "QFileDialog",
    "QFormLayout",
    "QFrame",
    "QGraphicsOpacityEffect",
    "QGridLayout",
    "QGroupBox",
    "QHBoxLayout",
    "QHeaderView",
    "QInputDialog",
    "QLabel",
    "QLineEdit",
    "QListWidget",
    "QListWidgetItem",
    "QMainWindow",
    "QMenu",
    "QMessageBox",
    "QPlainTextEdit",
    "QProgressBar",
    "QProgressDialog",
    "QPushButton",
    "QRadioButton",
    "QScrollArea",
    "QSizePolicy",
    "QSlider",
    "QSpacerItem",
    "QSplashScreen",
    "QSpinBox",
    "QSplitter",
    "QStackedWidget",
    "QStyle",
    "QTableWidget",
    "QTableWidgetItem",
    "QTabWidget",
    "QTextEdit",
    "QToolBar",
    "QToolButton",
    "QTreeWidget",
    "QTreeWidgetItem",
    "QVBoxLayout",
    "QWidget",
    # Multimedia
    "QAudioOutput",
    "QMediaPlayer",
    "MULTIMEDIA_AVAILABLE",
]
