/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TranscriptionRouteImport } from './routes/transcription'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordingRouteImport } from './routes/recording'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as WorkspaceDocumentIdRouteImport } from './routes/workspace.$documentId'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptionRoute = TranscriptionRouteImport.update({
  id: '/transcription',
  path: '/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingRoute = RecordingRouteImport.update({
  id: '/recording',
  path: '/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const WorkspaceDocumentIdRoute = WorkspaceDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recording': typeof RecordingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/transcription': typeof TranscriptionRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/settings/models': typeof SettingsModelsRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/workspace/$documentId': typeof WorkspaceDocumentIdRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recording': typeof RecordingRoute
  '/timeline': typeof TimelineRoute
  '/transcription': typeof TranscriptionRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/settings/models': typeof SettingsModelsRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/workspace/$documentId': typeof WorkspaceDocumentIdRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recording': typeof RecordingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/transcription': typeof TranscriptionRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/settings/models': typeof SettingsModelsRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/workspace/$documentId': typeof WorkspaceDocumentIdRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recording'
    | '/settings'
    | '/timeline'
    | '/transcription'
    | '/workspace'
    | '/settings/models'
    | '/settings/theme'
    | '/workspace/$documentId'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recording'
    | '/timeline'
    | '/transcription'
    | '/workspace'
    | '/settings/models'
    | '/settings/theme'
    | '/workspace/$documentId'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/recording'
    | '/settings'
    | '/timeline'
    | '/transcription'
    | '/workspace'
    | '/settings/models'
    | '/settings/theme'
    | '/workspace/$documentId'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordingRoute: typeof RecordingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TimelineRoute: typeof TimelineRoute
  TranscriptionRoute: typeof TranscriptionRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcription': {
      id: '/transcription'
      path: '/transcription'
      fullPath: '/transcription'
      preLoaderRoute: typeof TranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording': {
      id: '/recording'
      path: '/recording'
      fullPath: '/recording'
      preLoaderRoute: typeof RecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/workspace/$documentId': {
      id: '/workspace/$documentId'
      path: '/$documentId'
      fullPath: '/workspace/$documentId'
      preLoaderRoute: typeof WorkspaceDocumentIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceDocumentIdRoute: typeof WorkspaceDocumentIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceDocumentIdRoute: WorkspaceDocumentIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordingRoute: RecordingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TimelineRoute: TimelineRoute,
  TranscriptionRoute: TranscriptionRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
