# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2024-2025 EchoNote Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
UI Constants for EchoNote application.

Centralized constants to avoid hardcoding values throughout the UI layer.
"""

# Search widget constants
SEARCH_DEBOUNCE_DELAY_MS = 300
SEARCH_INPUT_MIN_WIDTH = 200
SEARCH_MATCH_LABEL_MIN_WIDTH = 100
LARGE_DOCUMENT_THRESHOLD = 50000

# Button size constants
ICON_BUTTON_MAX_WIDTH = 40
CONTROL_BUTTON_MIN_HEIGHT = 28
BATCH_SELECTOR_MIN_WIDTH = 138

# Notification constants
NOTIFICATION_RESET_DELAY_MS = 2000

# Layout constants (Standard 8px grid)
LAYOUT_SPACING = 8
DEFAULT_MARGINS = (12, 12, 12, 12)
DEFAULT_LAYOUT_SPACING = LAYOUT_SPACING
ZERO_SPACING = 0
ZERO_MARGINS = (0, 0, 0, 0)

# Main shell layout constants
APP_TOP_BAR_HEIGHT = 48
APP_STATUS_BAR_HEIGHT = 32
APP_SHELL_CONTENT_MARGINS = (8, 6, 8, 6)
APP_TOP_BAR_MARGINS = (12, 4, 12, 4)
APP_TOP_BAR_SPACING = 5
APP_STATUS_BAR_MARGINS = (12, 0, 12, 0)
APP_STATUS_BAR_SPACING = 14
APP_SEARCH_MIN_WIDTH = 180
APP_SEARCH_MAX_WIDTH = 260
APP_TOP_BAR_CONTROL_HEIGHT = 26
APP_TOP_BAR_HINT_WIDTH = 50
SHELL_STATUS_REFRESH_INTERVAL_MS = 2000

# Unified page density constants
PAGE_CONTENT_MARGINS = (10, 8, 10, 8)
PAGE_LAYOUT_SPACING = LAYOUT_SPACING
PAGE_COMPACT_SPACING = 6
PAGE_DENSE_SPACING = 4

# Realtime record layout constants
REALTIME_FORM_MARGINS = (12, 8, 12, 8)
REALTIME_FORM_HORIZONTAL_SPACING = 12
REALTIME_BUTTON_MIN_WIDTH = 84
REALTIME_RECORD_BUTTON_MIN_WIDTH = 96
REALTIME_LABEL_WIDTH_LARGE = 100
REALTIME_LABEL_WIDTH_MEDIUM = 80
REALTIME_COMBO_MIN_WIDTH = 180
REALTIME_LANGUAGE_COMBO_MIN_WIDTH = 136
REALTIME_GAIN_SLIDER_MIN_WIDTH = 150
REALTIME_GAIN_SLIDER_MAX_WIDTH = 200
REALTIME_GAIN_VALUE_MIN_WIDTH = 40
REALTIME_DEVICE_REFRESH_BUTTON_MIN_WIDTH = 72
REALTIME_DEVICE_REFRESH_INTERVAL_MS = 2500
SETTINGS_GAIN_VALUE_LABEL_MIN_WIDTH = 50
REALTIME_VISUALIZER_MIN_HEIGHT = 60
REALTIME_VISUALIZER_MAX_HEIGHT = 80
REALTIME_TEXT_TOOLBAR_META_SPACING = 8
REALTIME_FLOATING_MIN_WIDTH = 420
REALTIME_FLOATING_CONTENT_MARGINS = (14, 12, 14, 12)
REALTIME_FLOATING_LAYOUT_SPACING = 10
REALTIME_FLOATING_HEADER_SPACING = 8
REALTIME_FLOATING_PREVIEW_MIN_HEIGHT = 64

# Timeline constants
TIMELINE_SEARCH_NAV_BUTTON_MAX_WIDTH = 40
TIMELINE_TRANSLATION_COMBO_MIN_WIDTH = 120
TIMELINE_CURRENT_TIME_LINE_HEIGHT = 2
TIMELINE_VIEWER_SEARCH_ROW_SPACING = 6
TIMELINE_VIEWER_ACTION_ROW_SPACING = 8
TIMELINE_TRANSCRIPT_DIALOG_MIN_WIDTH = 600
TIMELINE_TRANSCRIPT_DIALOG_MIN_HEIGHT = 500
TIMELINE_DIALOG_BUTTON_MARGINS = (8, 0, 8, 8)

# Audio visualizer constants
AUDIO_VISUALIZER_MIN_HEIGHT = 100
AUDIO_VISUALIZER_MIN_WIDTH = 400

# Audio player constants
AUDIO_PLAYER_VOLUME_SLIDER_WIDTH = 100
AUDIO_PLAYER_PLAY_BUTTON_SIZE = 48
AUDIO_PLAYER_CONTROL_BUTTON_SIZE = 34
AUDIO_PLAYER_PLAY_ICON_SIZE = 20
AUDIO_PLAYER_CONTROL_ICON_SIZE = 16
AUDIO_PLAYER_DIALOG_MIN_WIDTH = 500
AUDIO_PLAYER_DIALOG_MIN_HEIGHT = 260
AUDIO_PLAYER_DIALOG_DEFAULT_WIDTH = 760
AUDIO_PLAYER_DIALOG_DEFAULT_HEIGHT = 360
AUDIO_PLAYER_DIALOG_EXPANDED_MIN_HEIGHT = 420
AUDIO_PLAYER_DIALOG_MARGIN = 20
AUDIO_PLAYER_DIALOG_SPACING = 16
AUDIO_PLAYER_TRANSCRIPT_AREA_HEIGHT = 200
AUDIO_PLAYER_HEADER_MAX_HEIGHT = 84
AUDIO_PLAYER_CONTROL_BAR_MAX_HEIGHT = 180
AUDIO_PLAYER_TRANSCRIPT_MIN_HEIGHT = 280
AUDIO_PLAYER_CONTENT_MARGIN = 16
AUDIO_PLAYER_CONTENT_SPACING = 6
AUDIO_PLAYER_CONTROL_BAR_SPACING = 10
AUDIO_PLAYER_CONTROLS_SPACING = 14
AUDIO_PLAYER_INFO_BOTTOM_MARGIN = 12
AUDIO_PLAYER_TRANSCRIPT_BOTTOM_MARGIN = 8

# Dialog constants
ERROR_DIALOG_MIN_WIDTH = 500
ERROR_DIALOG_DETAILS_MAX_HEIGHT = 200
FFMPEG_DIALOG_MIN_WIDTH = 600
FFMPEG_DIALOG_MIN_HEIGHT = 400
LOOPBACK_DIALOG_MIN_WIDTH = 600
LOOPBACK_DIALOG_MIN_HEIGHT = 420
CALENDAR_EVENT_DIALOG_MIN_WIDTH = 500
CALENDAR_EVENT_DESCRIPTION_MAX_HEIGHT = 100
CALENDAR_OAUTH_DIALOG_MIN_WIDTH = 500
CALENDAR_OAUTH_RESULT_DIALOG_MIN_WIDTH = 400
CALENDAR_OAUTH_INSTRUCTIONS_MAX_HEIGHT = 150
CALENDAR_ADD_ACCOUNT_DIALOG_MIN_WIDTH = 300
CALENDAR_DAY_CELL_MIN_HEIGHT = 80

# Dialog icon/title font constants
INSTALL_DIALOG_WARNING_ICON_FONT_SIZE = 32
INSTALL_DIALOG_HEADPHONE_ICON_FONT_SIZE = 28

# Splash screen constants
SPLASH_TITLE_FONT_SIZE = 24
SPLASH_VERSION_FONT_SIZE = 12
SPLASH_PROGRESS_FONT_SIZE = 11
SPLASH_BAR_HEIGHT = 20
SPLASH_HORIZONTAL_MARGIN = 20
SPLASH_PERCENT_RESERVED_WIDTH = 60

# Performance constants
MAX_SEARCH_RESULTS = 1000
PAGINATION_THRESHOLD = 0.8

# Theme constants
# HIGHLIGHT_COLORS and TIMELINE_SEARCH_HIGHLIGHT_COLOR moved to ThemeManager

# Role constants for semantic styling
ROLE_TIMELINE_SEARCH_INPUT = "timeline-search-input"
ROLE_TIMELINE_SEARCH_ACTION = "timeline-search-action"
ROLE_TIMELINE_FILTER_CONTROL = "timeline-filter-control"
ROLE_CURRENT_TIME_LINE = "current-time-line"
ROLE_CURRENT_TIME = "current-time"
ROLE_EVENT_TITLE = "event-title"
ROLE_EVENT_META = "event-meta"
ROLE_EVENT_TYPE_BADGE = "event-type-badge"
ROLE_EVENT_INDICATOR = "event-indicator"
ROLE_EVENT_DESCRIPTION = "event-description"
ROLE_DANGER = "danger"
ROLE_NO_ARTIFACTS = "no-artifacts"
ROLE_SYNC_STATUS = "sync-status"
ROLE_CALENDAR_VIEW_TOGGLE = "calendar-view-toggle"
ROLE_CALENDAR_NAV_ACTION = "calendar-nav-action"
ROLE_CALENDAR_PRIMARY_ACTION = "calendar-primary-action"
ROLE_CALENDAR_UTILITY_ACTION = "calendar-utility-action"

# Timeline Action Roles
ROLE_TIMELINE_RECORDING_ACTION = "timeline-recording-action"
ROLE_TIMELINE_TRANSCRIPT_ACTION = "timeline-transcript-action"
ROLE_TIMELINE_TRANSLATION_ACTION = "timeline-translation-action"
ROLE_TIMELINE_SECONDARY_TRANSCRIBE_ACTION = "timeline-secondary-transcribe-action"
ROLE_TIMELINE_COPY_ACTION = "timeline-copy-action"
ROLE_TIMELINE_EXPORT_ACTION = "timeline-export-action"

# Dialog and Generic Action Roles
ROLE_DIALOG_PRIMARY_ACTION = "dialog-primary-action"
ROLE_DIALOG_SECONDARY_ACTION = "dialog-secondary-action"
ROLE_DIALOG_NAV_ACTION = "dialog-nav-action"
ROLE_TOOLBAR_SECONDARY_ACTION = "toolbar-secondary-action"

# Transcript Roles
ROLE_TRANSCRIPT_FILE = "transcript-file"
ROLE_AUDIO_PLAYER_TRANSCRIPT_TITLE = "audio-player-transcript-title"
ROLE_AUDIO_PLAYER_TRANSCRIPT_TEXT = "audio-player-transcript-text"
ROLE_AUDIO_PLAYER_TRANSCRIPT_TOGGLE = "audio-player-transcript-toggle"
ROLE_AUDIO_PLAYER_PROGRESS = "audio-player-progress"
ROLE_AUDIO_PLAYER_TIME = "audio-player-time"
ROLE_AUDIO_PLAYER_VOLUME = "audio-player-volume"
ROLE_AUDIO_PLAYER_SURFACE = "audio-player-surface"
ROLE_AUDIO_PLAYER_TITLE = "audio-player-title"
ROLE_AUDIO_PLAYER_SUBTITLE = "audio-player-subtitle"
ROLE_AUDIO_PLAYER_DIVIDER = "audio-player-divider"
ROLE_AUDIO_PLAYER_MODE_CAPTION = "audio-player-mode-caption"
ROLE_AUDIO_PLAYER_MODE_ACTION = "audio-player-mode-action"
ROLE_AUDIO_PLAYER_TRANSCRIPT_PANEL = "audio-player-transcript-panel"

# Calendar Roles
ROLE_EVENT_CARD = "event-card"
ROLE_EVENT_TIME = "event-time"
ROLE_CALENDAR_HEADER = "calendar-header"
ROLE_CALENDAR_DAY_HEADER = "calendar-day-header"
ROLE_CALENDAR_DAY_CELL = "calendar-day-cell"
ROLE_CALENDAR_DAY_NUMBER = "calendar-day-number"
ROLE_MORE_EVENTS = "more-events"
ROLE_CALENDAR_WEEK_HEADER = "calendar-week-header"
ROLE_CALENDAR_DAY_COLUMN = "calendar-day-column"
ROLE_CALENDAR_EVENTS_CONTAINER = "calendar-events-container"
ROLE_NO_EVENTS = "no-events"

# Account and OAuth Roles
ROLE_OAUTH_STATUS = "oauth-status"
ROLE_ACCOUNT_BADGE = "account-badge"
ROLE_CALENDAR_INDICATOR = "calendar-indicator"
ROLE_ACCOUNT_DISCONNECT = "account-disconnect"

# Batch Task Roles
ROLE_TASK_ITEM = "task-item"
ROLE_TASK_FILENAME = "task-filename"
ROLE_TASK_INFO = "task-info"
ROLE_TASK_ERROR = "task-error"
ROLE_TASK_STATUS = "task-status"
ROLE_TASK_PERCENT = "task-percent"

# Task Action Roles
ROLE_TASK_ACTION_START = "task-action-start"
ROLE_TASK_ACTION_PAUSE = "task-action-pause"
ROLE_TASK_ACTION_CANCEL = "task-action-cancel"
ROLE_TASK_ACTION_DELETE = "task-action-delete"
ROLE_TASK_ACTION_VIEW = "task-action-view"
ROLE_TASK_ACTION_EXPORT = "task-action-export"
ROLE_TASK_ACTION_RETRY = "task-action-retry"

# Settings Roles
ROLE_AUTO_START_DESC = "auto-start-desc"
ROLE_DESCRIPTION = "description"
ROLE_MODEL_REASON = "model-reason"
ROLE_MODEL_DELETE = "model-delete"
ROLE_MODEL_DOWNLOAD = "model-download"
ROLE_TIME_DISPLAY = "time-display"
ROLE_MODEL_CONFIG_FIELD_LABEL = "model-config-field-label"
ROLE_CUDA_NOTE = "cuda-note"
ROLE_FFMPEG_STATUS = "ffmpeg-status"
ROLE_DEVICE_INFO = "device-info"
ROLE_SETTINGS_RESET_ACTION = "settings-reset-action"
ROLE_SETTINGS_CANCEL_ACTION = "settings-cancel-action"
ROLE_SETTINGS_SAVE_ACTION = "settings-save-action"
ROLE_SETTINGS_NAV = "settings-nav"
ROLE_AUDIO_PLAYER_CONTROL = "audio-player-control"
ROLE_AUDIO_PLAYER_PRIMARY = "audio-player-primary"
ROLE_SIDEBAR_NAV_BUTTON = "sidebar-nav-button"

# Realtime Record Roles
ROLE_REALTIME_DURATION = "realtime-duration"
ROLE_REALTIME_MARKER_ACTION = "realtime-marker-action"
ROLE_REALTIME_RECORD_ACTION = "realtime-record-action"
ROLE_REALTIME_FIELD_CONTROL = "realtime-field-control"
ROLE_REALTIME_FLOATING_OVERLAY = "realtime-floating-overlay"
ROLE_REALTIME_FLOATING_TITLE = "realtime-floating-title"
ROLE_REALTIME_FLOATING_STATUS = "realtime-floating-status"
ROLE_REALTIME_FLOATING_META = "realtime-floating-meta"
ROLE_REALTIME_FLOATING_SECTION_TITLE = "realtime-floating-section-title"
ROLE_REALTIME_FLOATING_PREVIEW = "realtime-floating-preview"
ROLE_REALTIME_FLOATING_ACTION = "realtime-floating-action"
ROLE_REALTIME_FLOATING_CLOSE = "realtime-floating-close"
ROLE_REALTIME_FLOATING_TOGGLE = "realtime-floating-toggle"
ROLE_FEEDBACK = "feedback"

# Advanced Settings Roles
ROLE_SETTINGS_INLINE = "settings-inline"
ROLE_SETTINGS_INLINE_ACTION = "settings-inline-action"
ROLE_SETTINGS_CONFIG_GROUP = "settings-config-group"
ROLE_SETTINGS_CONFIG_GROUP_NESTED = "settings-config-group-nested"
ROLE_USAGE_STATS = "usage-stats"
ROLE_WARNING_LARGE = "warning-large"

# Audio Roles
ROLE_AUDIO_FILE = "audio-file"

# Navigation symbols
NAV_SYMBOL_PREV = "<"
NAV_SYMBOL_NEXT = ">"

# Common display text
STATUS_INDICATOR_SYMBOL = "\u25cf"
DEFAULT_DURATION_DISPLAY = "00:00:00"
GAIN_DISPLAY_FORMAT = "{:.1f}x"


def format_gain_display(gain: float) -> str:
    """Format gain multiplier text consistently across UI pages."""
    return GAIN_DISPLAY_FORMAT.format(gain)


# Sidebar constants
SIDEBAR_WIDTH = 212
SIDEBAR_CONTAINER_MARGIN = 8
SIDEBAR_BUTTON_MIN_HEIGHT = 36
SIDEBAR_BUTTON_ICON_SIZE = 16

# Settings and list layout constants
SETTINGS_NAV_WIDTH = 168
SETTINGS_PREVIEW_MIN_HEIGHT = 150
CALENDAR_ACCOUNTS_LIST_MIN_HEIGHT = 200
CALENDAR_GRID_CELL_SPACING = 1
MODEL_MANAGEMENT_LIST_SPACING = 10
MODEL_MANAGEMENT_SECTION_TITLE_FONT_SIZE = 12
MODEL_MANAGEMENT_MODEL_NAME_FONT_SIZE = 11
MODEL_MANAGEMENT_ACTION_BUTTON_MAX_WIDTH_SMALL = 80
MODEL_MANAGEMENT_ACTION_BUTTON_MAX_WIDTH_MEDIUM = 100
MODEL_MANAGEMENT_RECOMMENDED_BUTTON_MAX_WIDTH = 200
MODEL_DETAILS_DIALOG_MIN_WIDTH = 500
MODEL_DETAILS_DIALOG_MIN_HEIGHT = 400
MODEL_CONFIG_DIALOG_MIN_WIDTH = 450

# Batch task item layout constants
TASK_ITEM_MIN_HEIGHT = 150

# Layout constants (extended)
LABEL_MIN_WIDTH = 120
STANDARD_LABEL_WIDTH = 200  # Standard width for form labels

# Gain slider constants (for realtime settings)
GAIN_SLIDER_MIN = 10  # 0.1 * 100 (minimum gain multiplier)
GAIN_SLIDER_MAX = 200  # 2.0 * 100 (maximum gain multiplier)
GAIN_SLIDER_DEFAULT = 100  # 1.0 * 100 (default gain multiplier)
GAIN_SLIDER_TICK_INTERVAL = 10  # Tick every 0.1x
GAIN_SLIDER_DIVISOR = 100.0  # Convert slider value to float
